jwt:
  access:
    expiration: ${JWT_ACCESS_EXP}
    header: ${JWT_ACCESS_HEADER}

  refresh:
    expiration: ${JWT_REFRESH_EXP}
    header: ${JWT_REFRESH_HEADER}

  secretKey: ${JWT_SECRET}

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect